# Generated by Django 4.2.5 on 2023-10-15 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Valoracion', '0003_alter_diagnostico_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_veh', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15)),
                ('lugarExpediplaca', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('modelo', models.CharField(max_length=25)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_val', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Valoracion.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Serviciosxvehiculos',
            fields=[
                ('id_serveh', models.AutoField(primary_key=True, serialize=False)),
                ('id_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehiculo.servicios')),
                ('id_veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehiculo.vehiculos')),
            ],
        ),
    ]
