# Generated by Django 4.2.5 on 2023-09-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.rol')),
            ],
        ),
    ]
