# Generated by Django 4.2.5 on 2023-09-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_usuario_last_login_alter_rol_id_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
