# Generated by Django 4.2.5 on 2023-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_val', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=3000)),
            ],
        ),
    ]
