# Generated by Django 4.2.5 on 2023-09-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Valoracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valoracion',
            new_name='Diagnostico',
        ),
    ]
