# Generated by Django 4.2.5 on 2023-10-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valoracion', '0002_rename_valoracion_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostico',
            field=models.CharField(max_length=8000),
        ),
    ]
